spring.application.name=MoviesApp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://postgresql://@dpg-cu69i4d6l47c73bvbni0-a.oregon-postgres.render.com/movies_db_bzdl
spring.datasource.username=movies_db_bzdl_user
spring.datasource.password=TGoHw2gJ6k5ASv6nbz8ukX1gPvxnoK7H
spring.datasource.driver-class-name=org.postgresql.Driver


# Your TMDB API key
tmdb.api.key=dec10c6ce5c76e827b9fedf46bb88f17

# TMDB Base URL
tmdb.base.url=https://api.themoviedb.org/3


omdb.api.key=3d843ea6

omdb.base.url=http://www.omdbapi.com
