# application-dev.properties

# Server
server.port=8080

# Database (Local)
spring.datasource.url=jdbc:postgresql://localhost:5432/movies_db
spring.datasource.username=postgres
spring.datasource.password=Arshath

# Redis (optional for local)
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis

# TMDB API
tmdb.api.key=dec10c6ce5c76e827b9fedf46bb88f17
tmdb.base.url=https://api.themoviedb.org/3
