# Server Configuration
server.port=${PORT:10000}

spring.application.name=MoviesApp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.open-in-view=false

# Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.max-lifetime=1800000

# Actuator (Optional)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d0pep2emcj7s73e2927g-a.oregon-postgres.render.com:5432/movies_db_0s6y
spring.datasource.username=movies_db_0s6y_user
spring.datasource.password=RY3v1mIwKzP3IhtgUG5TMvGc3uMkWuhB

# TMDB API
tmdb.api.key=${TMDB_API_KEY}
tmdb.base.url=https://api.themoviedb.org/3

# Redis (Optional, Local)
spring.redis.host={REDIS_HOST}
spring.redis.port=6379
spring.cache.type=redis



