spring.application.name=MoviesApp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG



# PostgreSQL Configurations
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# TMDB API Key
#tmdb.api.key=${TMDB_API_KEY}

# TMDB Base URL
tmdb.base.url=https://api.themoviedb.org/3


# Redis connection settings
spring.redis.host=${REDIS_URL}
spring.redis.password=${REDIS_PASSWORD}
spring.cache.type=redis







