# application-prod.properties

# Server
server.port=${PORT:10000}

# PostgreSQL (Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Redis (if used on Render)
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.cache.type=redis

# TMDB API
tmdb.api.key=${TMDB_API_KEY}
tmdb.base.url=https://api.themoviedb.org/3
